<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6fijlgx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6fijlgx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6fijlgx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6fijlgx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6fijlgx\appProdProjectContainer([
    'container.build_hash' => '6fijlgx',
    'container.build_id' => 'ecd5967a',
    'container.build_time' => 1555751421,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6fijlgx');
