<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRhrudsk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRhrudsk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRhrudsk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRhrudsk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRhrudsk\appDevDebugProjectContainer([
    'container.build_hash' => 'Rhrudsk',
    'container.build_id' => '3a52d9e0',
    'container.build_time' => 1555617633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRhrudsk');
